resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- env.yaml
- manager_webhook_patch.yaml
images:
- name: controller
  newName: quay.io/mmahmoud/controller
