---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ingress-nodefw-ingress-nodefw-v1alpha1-ingressnodefirewall
  failurePolicy: Fail
  name: vingressnodefirewall.kb.io
  rules:
  - apiGroups:
    - ingress-nodefw.ingress-nodefw
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressnodefirewalls
  sideEffects: None
