# Adds namespace to all resources.
namespace: openshift-ingress-node-firewall

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: ingress-node-firewall-

bases:
  - ../crd
  - ../rbac
  - ../manager
  - ../webhook
  - ../prometheus
  - namespace.yaml
  - rbac.yaml

patchesStrategicMerge:
  - patch.yaml
