# permissions for end users to edit ingressnodefirewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressnodefirewall-editor-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewalls/status
  verbs:
  - get
