# permissions for end users to edit ingrnodefwconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingrnodefwconfig-editor-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingrnodefwconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingrnodefwconfigs/status
  verbs:
  - get
