# permissions for end users to view ingrnodefwconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingrnodefwconfig-viewer-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingrnodefwconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingrnodefwconfigs/status
  verbs:
  - get
