---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ingress-nodefw.io.ingress-nodefw.io
  resources:
  - ingressnodefirewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.io.ingress-nodefw.io
  resources:
  - ingressnodefirewalls/finalizers
  verbs:
  - update
- apiGroups:
  - ingress-nodefw.io.ingress-nodefw.io
  resources:
  - ingressnodefirewalls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ingress-nodefw.io.ingress-nodefw.io
  resources:
  - nodeendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.io.ingress-nodefw.io
  resources:
  - nodeendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - ingress-nodefw.io.ingress-nodefw.io
  resources:
  - nodeendpoints/status
  verbs:
  - get
  - patch
  - update
