apiVersion: ingress-nodefw.io.ingress-nodefw.io/v1alpha1
kind: IngressNodeFirewall
metadata:
  name: ingressnodefirewall-sample
spec:
  interfaces:
  - eth0
  nodeSelector:
    do-node-ingress-firewall: 'true'
  ingress:
  - fromCIDRs:
       - 1.1.1.1/24
       - 100:1::1/64
    rules:
    - order: 10
      protocol: tcp
      protoRule:
        port: 100
      action: allow
    - order: 20
      protocol: udp
      protoRule:
        port: 8000
      action: allow
  - fromCIDRs:
       - 3.3.3.3/24
    rules:
    - order: 10
      protocol: icmp
      icmpRule:
        icmpType: 3 # Destination unreachable
        icmpCode: 1 # Host unreachable
      action: allow
  - fromCIDRs:
       - 10:10::1/64
    rules:
    - order: 10
      protocol: icmpv6
      icmpRule:
        icmpType: 128 # Ping request
      action: deny
  - fromCIDRs:
       - 0.0.0.0/0
       - 0::0/0
    rules:
    - order: 10
      protocol: tcp
      action: allow
