apiVersion: ingress-nodefw.ingress-nodefw/v1alpha1
kind: IngressNodeFirewall
metadata:
  name: ingressnodefirewall-demo2
spec:
  interfaces:
  - eth0
  nodeSelector:
    do-node-ingress-firewall: 'true'
  ingress:
  - sourceCIDRs:
       - 172.16.0.0/12
    rules:
    - order: 10
      protocol: icmp
      icmpRule:
        icmpType: 8 #ICMP Echo request
      action: deny
    - order: 20
      protocol: tcp
      protoRule:
        ports: "8000-9000"
      action: deny
  - sourceCIDRs:
       - fc00:f853:ccd:e793::0/64
    rules:
    - order: 10
      protocol: icmp6
      icmpRule:
        icmpType: 128 #ICMPV6 Echo request
      action: deny
